server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    default_type application/octet-stream;

    types {
        text/html                             html htm;
        text/css                              css;
        application/javascript                js;
        application/x-yaml                    yaml yml;
        image/svg+xml                         svg;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        add_header Cache-Control "no-cache";
        add_header Content-Type "application/x-yaml; charset=utf-8";
    }
}
